Documentation: 
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'app/**/*'
    - 'app/controllers/users_controller.rb'

Metrics/MethodLength:
  Max: 25
